---

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Create Market Data Collector Security Group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: Market Data Collector Group
        vpc_id: "{{ vpc_id }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        tags:
          Name: "{{ tag }}" 
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
            - 22
            - 3000
            cidr_ip: 0.0.0.0/0
            rule_desc: ssh, grafana

    - name: Create Ec2 Instance
      amazon.aws.ec2:
        key_name: ChristianAWS-KeyPair2021
        group: "{{ security_group_name }}"
        instance_type: t2.medium
        image: ami-0be2609ba883822ec 
        wait: yes
        wait_timeout: 600
        volumes:
          - device_name: /dev/xvda
            delete_on_termination: yes
            volume_type: gp2
            volume_size: 30
        vpc_subnet_id: subnet-128bb839
        assign_public_ip: yes
        instance_tags:
          Name: "{{ tag }}" 
        count_tag:
          Name: "{{ tag }}" 
        exact_count: 1
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
      register: ec2

    - name: Add newly created ec2 Instance to hosts
      add_host:
        name: '{{ item.public_dns_name }}'
        groups: ec2_group
      loop: "{{ ec2.tagged_instances }}"        

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 600
      loop: "{{ ec2.tagged_instances }}"
      environment:
        ANSIBLE_HOST_KEY_CHECKING: False