- name: Configure GO
  hosts: ec2_group
  gather_facts: True
  remote_user: ec2-user

  tasks:

    - name: Check if GO is installed
      stat:
        path: /apps/go/go
      register: go

    - debug:
        msg: "Go Exists {{ go }}"

    - name: Create GO Directory
      file:
        path: /apps/go
        state: directory
        owner: ec2-user
        group: ec2-user
      become: yes
      when: not go.stat.exists 

    - name: Download GO Binary
      get_url:
        url: https://golang.org/dl/{{ go_rpm }}
        dest: /apps/go/{{ go_rpm }}
      when: not go.stat.exists

    - name: Extract GO
      unarchive:
        src: /apps/go/{{ go_rpm }}
        dest: /apps/go
        remote_src: yes
        creates: /apps/go/go
      when: not go.stat.exists 

    - name: Remote GO Binary
      stat:
        path: /apps/go/{{ go_rpm }}
      register: go_bin

    - name: Delete GO Binary
      file:
        path: /apps/go/{{ go_rpm }}
        state: absent
      when: go_bin.stat.exists